name: Release
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    timeout-minutes: 25
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.1
      - name: Setup Git
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Install Dependencies
        run: |
          npm ci
      - name: Version
        run: |
          npm version patch
      - name: Build
        run: npm run build
      - name: Publish NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./dist/package.json
      - name: Publish Github Packages
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package: ./dist/package.json
          registry: https://npm.pkg.github.com