name: Release Novo Elements
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-16.04
    timeout-minutes: 25
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.1
      - name: Install Dependencies
        run: |
          npm ci
      - name: Version
        run: |
          npm version patch
      - name: Commit & Push Token
        uses: actions-js/push@v1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
      - name: Build
        run: |
          npm run build:ci
      - name: Publish
        run: |
          cd dist
          npm publish