name: Release Novo Elements
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    timeout-minutes: 25
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.1
      - name: Setup Git
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Install Dependencies
        run: |
          npm ci
      - name: Version
        run: |
          npm version patch
      - name: Commit & Push Token
        uses: actions-js/push@v1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
      - name: Build
        run: |
          npm run build
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd dist
          npm publish